name: Create ADO release Issue

on:
  push:
  #schedule:
  #  - cron: '0 0 * * 1'
  # You can manually run this action w/:
  # curl -i -H 'Authorization: token <insert PAT token>' --request POST --data '{"event_type": "adorelease"}' https://api.github.com/repos/github/c2c-actions-compute-sre/dispatches
  repository_dispatch:
    types: adorelease

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
