name: CI

# on: [push]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos, macos-latest]

    steps:
    - name: Output Version
      run: sw_vers
    - name: Check jq
      run: |
        jq --version
      shell: bash
    
